/**
 * Spanish translations of the most common 5e.tools names. The 5etools data
 * is the source of truth; we apply this on top to display the names the
 * Spanish-speaking user expects. Anything not in the map falls back to
 * the English name.
 *
 * Keep this list small and high-value (player-facing records). The full
 * SRD 5.2 doesn't have official Spanish names, so we follow the 5etools
 * Spanish community translation where available.
 */
export const MONSTER_NAME_ES: Record<string, string> = {
  // SRD 5.2 / PHB / MM common monsters
  'Goblin': 'Goblin',
  'Orc': 'Orco',
  'Hobgoblin': 'Hobgoblin',
  'Kobold': 'Kóbold',
  'Gnoll': 'Gnoll',
  'Lizardfolk': 'Pueblo lagarto',
  'Bugbear': 'Insectópodo',
  'Ogre': 'Ogro',
  'Troll': 'Trol',
  'Skeleton': 'Esqueleto',
  'Zombie': 'Zombi',
  'Ghoul': 'Espectro devorador',
  'Wight': 'No-muerto',
  'Wraith': 'Ánima en pena',
  'Specter': 'Espectro',
  'Shadow': 'Sombra',
  'Vampire': 'Vampiro',
  'Lich': 'Liche',
  'Beholder': 'Beholder',
  'Mimic': 'Mímico',
  'Mind Flayer': 'Devorador de mentes',
  'Beholder Zombie': 'Beholder zombi',
  'Death Knight': 'Caballero de la muerte',
  'Mummy': 'Momia',
  'Minotaur': 'Minotauro',
  'Harpy': 'Arpía',
  'Centaur': 'Centauro',
  'Gargoyle': 'Gárgola',
  'Giant Spider': 'Araña gigante',
  'Giant Rat': 'Rata gigante',
  'Giant Constrictor Snake': 'Serpiente constrictora gigante',
  'Giant Scorpion': 'Escorpión gigante',
  'Giant Boar': 'Jabalí gigante',
  'Giant Eagle': 'Águila gigante',
  'Giant Owl': 'Búho gigante',
  'Giant Hyena': 'Hiena gigante',
  'Giant Frog': 'Rana gigante',
  'Giant Lizard': 'Lagarto gigante',
  'Giant Toad': 'Sapo gigante',
  'Giant Vulture': 'Buitre gigante',
  'Brown Bear': 'Oso pardo',
  'Black Bear': 'Oso negro',
  'Polar Bear': 'Oso polar',
  'Dire Wolf': 'Lobo terrible',
  'Wolf': 'Lobo',
  'Worg': 'Worg',
  'Lion': 'León',
  'Tiger': 'Tigre',
  'Mastiff': 'Mastín',
  'Riding Horse': 'Caballo de montar',
  'Horse': 'Caballo',
  'Draft Horse': 'Caballo de tiro',
  'Elephant': 'Elefante',
  'Mammoth': 'Mamut',
  'Rhinoceros': 'Rinoceronte',
  'Cat': 'Gato',
  'Poisonous Snake': 'Serpiente venenosa',
  'Crawling Claw': 'Garra reptante',
  'Flying Snake': 'Serpiente voladora',
  'Stirge': 'Mosca chupasangre',
  'Rat': 'Rata',
  'Raven': 'Cuervo',
  'Owl': 'Búho',
  'Eagle': 'Águila',
  'Hyena': 'Hiena',
  'Jackal': 'Chacal',
  'Blood Hawk': 'Halcón de sangre',
  'Pseudodragon': 'Pseudodragón',
  'Quipper': 'Quipper',
  'Giant Crab': 'Cangrejo gigante',
  'Pony': 'Poni',
  'Goat': 'Cabra',
  'Mule': 'Mula',
  'Donkey': 'Burro',
  'Ox': 'Buey',
  'Guard': 'Guardia',
  'Acolyte': 'Acólito',
  'Bandit': 'Bandido',
  'Bandit Captain': 'Capitán de bandidos',
  'Thug': 'Matón',
  'Spy': 'Espía',
  'Cultist': 'Cultista',
  'Cult Fanatic': 'Fanático del culto',
  'Veteran': 'Veterano',
  'Knight': 'Caballero',
  'Gladiator': 'Gladiador',
  'Mage': 'Mago',
  'Apprentice Wizard': 'Mago aprendiz',
  'Druid': 'Druida',
  'Archmage': 'Archimago',
  'Priest': 'Sacerdote',
  'Assassin': 'Asesino',
  'Thief': 'Ladrón',
  'Kobold Inventor': 'Inventor kóbold',
  'Kobold Scale Sorcerer': 'Hechicero kóbold',
  'Wererat': 'Hombre-rata',
  'Werewolf': 'Hombre-lobo',
  'Werebear': 'Hombre-oso',
  'Wereboar': 'Hombre-jabalí',
  'Weretiger': 'Hombre-tigre',
  'Drow': 'Drow',
  'Duergar': 'Duergar',
  'Svirfneblin': 'Svirfneblin',
  'Fire Elemental': 'Elemental de fuego',
  'Water Elemental': 'Elemental de agua',
  'Earth Elemental': 'Elemental de tierra',
  'Air Elemental': 'Elemental de aire',
  'Magmin': 'Mefita de fuego',
  'Ice Mephit': 'Mefita de hielo',
  'Dust Mephit': 'Mefita de polvo',
  'Magma Mephit': 'Mefita de magma',
  'Steam Mephit': 'Mefita de vapor',
  'Smoke Mephit': 'Mefita de humo',
  'Flesh Golem': 'Golem de carne',
  'Clay Golem': 'Golem de arcilla',
  'Stone Golem': 'Golem de piedra',
  'Iron Golem': 'Golem de hierro',
  'Animated Armor': 'Armadura animada',
  'Flying Sword': 'Espada voladora',
  'Rug of Smothering': 'Alfombra asfixiante',
  'Giant Centipede': 'Ciempiés gigante',
  'Pteranodon': 'Pteranodón',
  'Quetzal': 'Quetzal',
  'Plesiosaurus': 'Plesiosaurio',
  'Giant Sea Horse': 'Caballo marino gigante',
  'Giant Octopus': 'Pulpo gigante',
  'Giant Squid': 'Calamar gigante',
  'Giant Shark': 'Tiburón gigante',
  'Hunter Shark': 'Tiburón cazador',
  'Killer Whale': 'Orca',
  'Pliosaurus': 'Pliosaurio',
  'Dinosaur': 'Dinosaurio',
  'Velociraptor': 'Velociraptor',
  'Allosaurus': 'Allosaurus',
  'Triceratops': 'Triceratops',
  'Tyrannosaurus Rex': 'Tiranosaurio rex',
  'Stegosaurus': 'Estegosaurio',
  'Ankylosaurus': 'Ankylosaurus',
  'Brontosaurus': 'Brontosaurio',
  'Ape': 'Simio',
  'Baboon': 'Babuino',
  'Giant Ape': 'Simio gigante',
  'Crocodile': 'Cocodrilo',
  'Giant Crocodile': 'Cocodrilo gigante',
  'Constrictor Snake': 'Serpiente constrictora',
  'Swarm of Insects': 'Enjambre de insectos',
  'Swarm of Poisonous Snakes': 'Enjambre de serpientes venenosas',
  'Swarm of Spiders': 'Enjambre de arañas',
  'Swarm of Rats': 'Enjambre de ratas',
  'Swarm of Bats': 'Enjambre de murciélagos',
  'Swarm of Quippers': 'Enjambre de quippers',
  'Swarm of Cranium Rats': 'Enjambre de ratas cráneo',
  'Evil Mage': 'Mago malvado',
  'Grimlock': 'Grimlock',
  'Sahuagin': 'Sahuagin',
  'Merfolk': 'Pueblo del mar',
  'Grung': 'Grung',
  'Bullywug': 'Rana matona',
  'Guard Drake': 'Dracoguardia',
  'Cranium Rat': 'Rata cráneo',
  'Death Dog': 'Perro de la muerte',
  'Ettercap': 'Araña estranguladora',
  'Giant Spider (V)': 'Araña gigante (V)',
  'Giant Wasp': 'Avispa gigante',
  'Needle Blight': 'Espina corruptora',
  'Twig Blight': 'Ramita corruptora',
  'Vine Blight': 'Enredadera corruptora',
  'Banshee': 'Banshee',
  'Bodak': 'Bodak',
  'Devourer': 'Devorador',
  'Flameskull': 'Cráneo flamígero',
  'Ghost': 'Fantasma',
  'Helmed Horror': 'Horror acorazado',
  'Mummy Lord': 'Señor momia',
  'Nagpa': 'Nagpa',
  'Night Hag': 'Bruja nocturna',
  'Revenant': 'Vengador',
  'Shade': 'Sombra',
  'Shadow Dragon': 'Dragón sombrío',
  'Soul Monger': 'Comedor de almas',
  'Vampire Spawn': 'Engendro de vampiro',
  'Will-o\'-Wisp': 'Fuego fatuo',
  'Boneclaw': 'Garra ósea',
  'Cadaver Collector': 'Coleccionista de cadáveres',
  'Dread Warrior': 'Guerrero del pavor',
  'Deathlock': 'Cerradura mortal',
  'Drow Elite Warrior': 'Drow guerrero de élite',
  'Drow Mage': 'Drow mago',
  'Drow Priestess of Lolth': 'Drow sacerdotisa de Lolth',
  'Hobgoblin Devastator': 'Hobgoblin devastador',
  'Hobgoblin Iron Shadow': 'Hobgoblin sombra de hierro',
  'Bugbear Chief': 'Jefe insectópodo',
  'Stone Giant': 'Gigante de piedra',
  'Hill Giant': 'Gigante de las colinas',
  'Frost Giant': 'Gigante de hielo',
  'Fire Giant': 'Gigante de fuego',
  'Cloud Giant': 'Gigante de las nubes',
  'Storm Giant': 'Gigante de la tormenta',
  'Ettin': 'Ettin',
  'Ogre Bolt Launcher': 'Lanzador de pernos ogro',
  'Ogre Chain Brute': 'Ogro brutal de cadenas',
  'Ogre Howdah': 'Ogro Howdah',
  'Oni': 'Oni',
  'Frost Giant Everlasting One': 'Gigante de hielo eterno',
  'Fire Giant Dreadnought': 'Gigante de fuego acorazado',
  'Adult Black Dragon': 'Dragón negro adulto',
  'Adult Blue Dragon': 'Dragón azul adulto',
  'Adult Brass Dragon': 'Dragón de bronce adulto',
  'Adult Bronze Dragon': 'Dragón de latón adulto',
  'Adult Copper Dragon': 'Dragón de cobre adulto',
  'Adult Gold Dragon': 'Dragón dorado adulto',
  'Adult Green Dragon': 'Dragón verde adulto',
  'Adult Red Dragon': 'Dragón rojo adulto',
  'Adult Silver Dragon': 'Dragón plateado adulto',
  'Adult White Dragon': 'Dragón blanco adulto',
  'Ancient Black Dragon': 'Dragón negro anciano',
  'Ancient Blue Dragon': 'Dragón azul anciano',
  'Ancient Brass Dragon': 'Dragón de bronce anciano',
  'Ancient Bronze Dragon': 'Dragón de latón anciano',
  'Ancient Copper Dragon': 'Dragón de cobre anciano',
  'Ancient Gold Dragon': 'Dragón dorado anciano',
  'Ancient Green Dragon': 'Dragón verde anciano',
  'Ancient Red Dragon': 'Dragón rojo anciano',
  'Ancient Silver Dragon': 'Dragón plateado anciano',
  'Ancient White Dragon': 'Dragón blanco anciano',
  'Young Black Dragon': 'Dragón negro joven',
  'Young Blue Dragon': 'Dragón azul joven',
  'Young Brass Dragon': 'Dragón de bronce joven',
  'Young Bronze Dragon': 'Dragón de latón joven',
  'Young Copper Dragon': 'Dragón de cobre joven',
  'Young Gold Dragon': 'Dragón dorado joven',
  'Young Green Dragon': 'Dragón verde joven',
  'Young Red Dragon': 'Dragón rojo joven',
  'Young Silver Dragon': 'Dragón plateado joven',
  'Young White Dragon': 'Dragón blanco joven',
  'Black Dragon Wyrmling': 'Cría de dragón negro',
  'Blue Dragon Wyrmling': 'Cría de dragón azul',
  'Green Dragon Wyrmling': 'Cría de dragón verde',
  'Red Dragon Wyrmling': 'Cría de dragón rojo',
  'White Dragon Wyrmling': 'Cría de dragón blanco',
  'Brass Dragon Wyrmling': 'Cría de dragón de bronce',
  'Bronze Dragon Wyrmling': 'Cría de dragón de latón',
  'Copper Dragon Wyrmling': 'Cría de dragón de cobre',
  'Gold Dragon Wyrmling': 'Cría de dragón dorado',
  'Silver Dragon Wyrmling': 'Cría de dragón plateado',
  'Death Tyrant': 'Tirano de la muerte',
  'Mind Flayer Lich': 'Liche devoradora de mentes',
  'Mind Flayer Arcanist': 'Arcanista devorador de mentes',
  'Ulitharid': 'Ulitharid',
  'Aboleth': 'Aboleth',
  'Aboleth Myrmidons': 'Mirmidones aboleth',
  'Cloaker': 'Capa',
  'Demilich': 'Demiliche',
  'Dracolich': 'Dracoliche',
  'Gauth': 'Gauth',
  'Gibbering Mouther': 'Boca farfullante',
  'Grell': 'Grell',
  'Gynosphinx': 'Ginofinge',
  'Hippogriff': 'Hipogrifo',
  'Griffon': 'Grifo',
  'Manticore': 'Mantícora',
  'Manticora (V)': 'Mantícora (V)',
  'Naga, Bone': 'Naga ósea',
  'Naga, Guardian': 'Naga guardiana',
  'Naga, Spirit': 'Naga espiritual',
  'Naga, Water': 'Naga acuática',
  'Neogi': 'Neogi',
  'Neothelid': 'Neothelid',
  'Otyugh': 'Otyugh',
  'Pegasus': 'Pegaso',
  'Peryton': 'Peritón',
  'Purple Worm': 'Gusano violeta',
  'Roc': 'Roc',
  'Roper': 'Roper',
  'Sphinx (V)': 'Esfinge (V)',
  'Androsphinx': 'Androsfinge',
  'Spring': 'Trampa de resorte',
  'Sword (V)': 'Espada',
  'Unicorn': 'Unicornio',
  'Vargouille': 'Vargouille',
  'Wyvern': 'Vibora alada',
  'Balor': 'Balor',
  'Barbed Devil': 'Diablo con púas',
  'Bearded Devil': 'Diablo barbudo',
  'Bone Devil': 'Diablo de hueso',
  'Chain Devil': 'Diablo de cadenas',
  'Erinyes': 'Erinia',
  'Glabrezu': 'Glabrezu',
  'Horned Devil': 'Diablo cornudo',
  'Ice Devil': 'Diablo de hielo',
  'Imp': 'Diablillo',
  'Lemure': 'Lemur',
  'Marilith': 'Marilith',
  'Nalfeshnee': 'Nalfeshnee',
  'Pit Fiend': 'Abismo de la fosa',
  'Quasit': 'Quasit',
  'Spined Devil': 'Diablo espinoso',
  'Vrock': 'Vrock',
  'Abyssal Chicken': 'Pollo abisal',
  'Demon Lord': 'Señor demonio',
  'Deva': 'Deva',
  'Empyrean': 'Empíreo',
  'Ki-rin': 'Ki-rin',
  'Planetar': 'Planetar',
  'Solar': 'Solar',
  'Couatl': 'Couatl',
  'Eagle (V)': 'Águila',
  'Dretch': 'Dretch',
  'Hezrou': 'Hezrou',
  'Manes': 'Manes',
  'Shadow Demon': 'Demonio sombrío',
  'Succubus/Incubus': 'Súcubo/Íncubo',
  'Kraken': 'Kraken',
  'Lamia': 'Lamia',
  'Lizard King': 'Rey lagarto',
  'Lizard Queen': 'Reina lagarto',
  'Medusa': 'Medusa',
  'Sprite': 'Hada',
  'Dryad': 'Dríada',
  'Awakened Tree': 'Árbol despierto',
  'Treant': 'Treant',
  'Myconid Sprout': 'Brote de miconido',
  'Myconid Adult': 'Miconido adulto',
  'Myconid Sovereign': 'Soberano miconido',
  'Vegepygmy': 'Vegepigmeo',
  'Vegepygmy Chief': 'Jefe vegepigmeo',
  'Shambling Mound': 'Montículo ambulante',
  'Blink Dog': 'Perro parpadeante',
  'Giant Frog (V)': 'Rana gigante',
  'Giant Crab (V)': 'Cangrejo gigante',
  'Homunculus': 'Homúnculo',
  'Aarakocra': 'Aarakocra',
  'Kenku': 'Kenku',
  'Tabaxi': 'Tabaxi',
  'Tortle': 'Tortle',
  'Triton': 'Tritón',
  'Goliath': 'Goliath',
  'Githyanki': 'Githyanki',
  'Githzerai': 'Githzerai',
  'Aasimar': 'Aasimar',
  'Genasi': 'Genasi',
  'Tiefling': 'Tiefling',
  'Yuan-ti': 'Yuan-ti',
  'Yuan-ti Abomination': 'Abominación yuan-ti',
  'Yuan-ti Malison': 'Malison yuan-ti',
  'Yuan-ti Mind Whisperer': 'Susurrador yuan-ti',
  'Yuan-ti Nightmare Speaker': 'Hablador de pesadillas yuan-ti',
  'Yuan-ti Pureblood': 'Pura sangre yuan-ti',
  'Quaggoth': 'Quaggoth',
  'Thri-kreen': 'Thri-kreen',
  'Centaur (V)': 'Centauro',
  'Minotaur (V)': 'Minotauro',
  'Satyr': 'Sátiro',
  'Drow (V)': 'Drow',
  'Duergar (V)': 'Duergar',
  'Svirfneblin (V)': 'Svirfneblin',
  'Sea Hag': 'Vieja del mar',
  'Green Hag': 'Vieja verde',
  'Annis Hag': 'Annis',
  'Bheur Hag': 'Bheur',
  'Red Hag': 'Vieja roja',
  'Hag (V)': 'Vieja',
  'Hag, Blood': 'Vieja de sangre',
  'Hag, Bile': 'Vieja de hiel',
  'Hag, Bone': 'Vieja de hueso',
  'Hag, Fever': 'Vieja de fiebre',
  'Hag, Gloom': 'Vieja de tiniebla',
  'Hag, Sea': 'Vieja del mar',
  'Hag, Slithering': 'Vieja deslizante',
  'Hag, Sun': 'Vieja del sol',
  'Hag, Dream': 'Vieja de sueños',
  'Hag, Green': 'Vieja verde',
  'Hag, Night': 'Bruja nocturna',
  'Hag, Annis': 'Annis',
  'Hag, Bheur': 'Bheur',
  'Lamia (V)': 'Lamia',
  'Succubus/Incubus (V)': 'Súcubo/Íncubo',
  'Erinyes (V)': 'Erinia',
  'Behir': 'Behir',
  'Bulette': 'Bulette',
  'Basilisk': 'Basilisco',
  'Cockatrice': 'Cocatriz',
  'Gorgon': 'Gorgo',
  'Chimera': 'Quimera',
  'Manticore (V)': 'Mantícora',
  'Girallon': 'Girallón',
  'Bulette (V)': 'Bulette',
  'Death Dog (V)': 'Perro de la muerte',
  'Worg (V)': 'Worg',
  'Giant Boar (V)': 'Jabalí gigante',
  'Giant Elk': 'Alce gigante',
  'Giant Owl (V)': 'Búho gigante',
  'Giant Vulture (V)': 'Buitre gigante',
  'Giant Wasp (V)': 'Avispa gigante',
  'Giant Weasel': 'Comadreja gigante',
  'Giant Rat (V)': 'Rata gigante',
  'Giant Hyena (V)': 'Hiena gigante',
  'Blood Hawk (V)': 'Halcón de sangre',
  'Pteranodon (V)': 'Pteranodón',
  'Quetzal (V)': 'Quetzal',
  'Awakened Animal': 'Animal despierto',
  'Awakened Shrub': 'Arbusto despierto',
  'Awakened Tree (V)': 'Árbol despierto',
  'Cranium Rat (V)': 'Rata cráneo',
  'Swarm of Insects (V)': 'Enjambre de insectos',
  'Swarm of Spiders (V)': 'Enjambre de arañas',
  'Swarm of Rats (V)': 'Enjambre de ratas',
  'Swarm of Bats (V)': 'Enjambre de murciélagos',
  'Swarm of Quippers (V)': 'Enjambre de quippers',
  'Swarm of Poisonous Snakes (V)': 'Enjambre de serpientes venenosas',
  'Swarm of Cranium Rats (V)': 'Enjambre de ratas cráneo',
  'Homunculus (V)': 'Homúnculo',
  'Imp (V)': 'Diablillo',
  'Pseudodragon (V)': 'Pseudodragón',
  'Quasit (V)': 'Quasit',
  'Sprite (V)': 'Hada',
  'Flying Snake (V)': 'Serpiente voladora',
  'Dinosaur (V)': 'Dinosaurio',
  'Velociraptor (V)': 'Velociraptor',
  'Allosaurus (V)': 'Allosaurus',
  'Triceratops (V)': 'Triceratops',
  'Tyrannosaurus Rex (V)': 'Tiranosaurio rex',
  'Stegosaurus (V)': 'Estegosaurio',
  'Ankylosaurus (V) =>': 'Ankylosaurus',
  'Plesiosaurus (V)': 'Plesiosaurio',
  'Brontosaurus (V)': 'Brontosaurio',
  'Giant Sea Horse (V)': 'Caballo marino gigante',
  'Giant Octopus (V)': 'Pulpo gigante',
  'Giant Squid (V)': 'Calamar gigante',
  'Giant Shark (V)': 'Tiburón gigante',
  'Hunter Shark (V)': 'Tiburón cazador',
  'Killer Whale (V)': 'Orca',
  'Crocodile (V)': 'Cocodrilo',
  'Giant Crocodile (V)': 'Cocodrilo gigante',
  'Constrictor Snake (V)': 'Serpiente constrictora',
  'Poisonous Snake (V)': 'Serpiente venenosa',
  'Ape (V)': 'Simio',
  'Giant Ape (V)': 'Simio gigante',
  'Baboon (V)': 'Babuino',
  'Mule (V)': 'Mula',
  'Donkey (V)': 'Burro',
  'Ox (V)': 'Buey',
  'Pony (V)': 'Poni',
  'Draft Horse (V)': 'Caballo de tiro',
  'Riding Horse (V)': 'Caballo de montar',
  'Goat (V)': 'Cabra',
  'Raven (V)': 'Cuervo',
  'Owl (V)': 'Búho',
  'Rat (V)': 'Rata',
  'Cat (V)': 'Gato',
  'Mastiff (V)': 'Mastín',
  'Lion (V)': 'León',
  'Tiger (V)': 'Tigre',
  'Brown Bear (V)': 'Oso pardo',
  'Black Bear (V)': 'Oso negro',
  'Polar Bear (V)': 'Oso polar',
  'Wolf (V)': 'Lobo',
  'Dire Wolf (V)': 'Lobo terrible',
  'Hyena (V)': 'Hiena',
  'Jackal (V)': 'Chacal',
  'Commoner': 'Aldeano',
  'Bandit (V)': 'Bandido',
  'Bandit Captain (V)': 'Capitán de bandidos',
  'Thug (V)': 'Matón',
  'Spy (V)': 'Espía',
  'Acolyte (V)': 'Acólito',
  'Priest (V)': 'Sacerdote',
  'Cultist (V)': 'Cultista',
  'Cult Fanatic (V)': 'Fanático del culto',
  'Apprentice Wizard (V)': 'Mago aprendiz',
  'Mage (V)': 'Mago',
  'Archmage (V)': 'Archimago',
  'Druid (V)': 'Druida',
  'Veteran (V)': 'Veterano',
  'Knight (V)': 'Caballero',
  'Guard (V)': 'Guardia',
  'Gladiator (V)': 'Gladiador',
  'Assassin (V)': 'Asesino',
  'Thief (V)': 'Ladrón',
};

/** Spanish translations of common 5e.tools spell names. */
export const SPELL_NAME_ES: Record<string, string> = {
  'Acid Splash': 'Rociada ácida',
  'Aid': 'Auxilio',
  'Alarm': 'Alarma',
  'Alter Self': 'Alterar uno mismo',
  'Animal Friendship': 'Amistad animal',
  'Animal Shapes': 'Formas animales',
  'Animate Dead': 'Animar muertos',
  'Animate Objects': 'Animar objetos',
  'Antilife Shell': 'Caparazón anti-vida',
  'Antimagic Field': 'Campo antimagia',
  'Antipathy/Sympathy': 'Antipatía/Simpatía',
  'Arcane Eye': 'Ojo arcano',
  'Arcane Hand': 'Mano arcana',
  'Arcane Lock': 'Cerradura arcana',
  'Arcane Sword': 'Espada arcana',
  'Arcanist\'s Magic Aura': 'Aura arcana del arcanista',
  'Astral Projection': 'Proyección astral',
  'Augury': 'Augurio',
  'Awaken': 'Despertar',
  'Bane': 'Azote',
  'Banishment': 'Destierro',
  'Barkskin': 'Piel de árbol',
  'Beacon of Hope': 'Faro de esperanza',
  'Bestow Curse': 'Imponer maldición',
  'Bigby\'s Hand': 'Mano de Bigby',
  'Blade Barrier': 'Barrera de cuchillas',
  'Blade Ward': 'Guardia de arma',
  'Bless': 'Bendición',
  'Blight': 'Agostar',
  'Blindness/Deafness': 'Ceguera/Sordera',
  'Blink': 'Parpadeo',
  'Blur': 'Difuminar',
  'Burning Hands': 'Manos ardientes',
  'Call Lightning': 'Llamar al rayo',
  'Calm Emotions': 'Calmar emociones',
  'Chain Lightning': 'Relámpago en cadena',
  'Charm Person': 'Encantar persona',
  'Chill Touch': 'Toque helado',
  'Chromatic Orb': 'Orbe cromático',
  'Circle of Death': 'Círculo de muerte',
  'Circle of Power': 'Círculo de poder',
  'Clairvoyance': 'Clarividencia',
  'Clone': 'Clon',
  'Cloud of Daggers': 'Nube de dagas',
  'Cloudkill': 'Nube mortífera',
  'Color Spray': 'Rocío de color',
  'Command': 'Orden',
  'Commune': 'Comulgar',
  'Compelled Duel': 'Duelo forzado',
  'Comprehend Languages': 'Comprender idiomas',
  'Compulsion': 'Compulsión',
  'Cone of Cold': 'Cono de frío',
  'Confusion': 'Confusión',
  'Conjure Animals': 'Convocar animales',
  'Conjure Celestial': 'Convocar celestial',
  'Conjure Elemental': 'Convocar elemental',
  'Conjure Fey': 'Convocar hadas',
  'Conjure Minor Elementals': 'Convocar elementales menores',
  'Conjure Woodland Beings': 'Convocar seres del bosque',
  'Contact Other Plane': 'Contactar otro plano',
  'Contagion': 'Contagio',
  'Contingency': 'Contingencia',
  'Continual Flame': 'Llama continua',
  'Control Water': 'Controlar agua',
  'Control Weather': 'Controlar clima',
  'Cordon of Arrows': 'Cordón de flechas',
  'Counterspell': 'Contrahechizo',
  'Create Food and Water': 'Crear comida y agua',
  'Create or Destroy Water': 'Crear o destruir agua',
  'Create Undead': 'Crear no-muerto',
  'Creation': 'Creación',
  'Crown of Stars': 'Corona de estrellas',
  'Cure Wounds': 'Curar heridas',
  'Dancing Lights': 'Luces danzantes',
  'Darkness': 'Oscuridad',
  'Darkvision': 'Visión en la oscuridad',
  'Daylight': 'Luz del día',
  'Death Ward': 'Protección contra muerte',
  'Delayed Blast Fireball': 'Bola de fuego de detonación retardada',
  'Demiplane': 'Semiplano',
  'Destructive Wave': 'Ola destructiva',
  'Detect Evil and Good': 'Detectar malignidad y bondad',
  'Detect Magic': 'Detectar magia',
  'Detect Poison and Disease': 'Detectar veneno y enfermedad',
  'Detect Thoughts': 'Detectar pensamientos',
  'Dimension Door': 'Puerta dimensional',
  'Disguise Self': 'Disfrazarse',
  'Disintegrate': 'Desintegrar',
  'Dispel Evil and Good': 'Disipar malignidad y bondad',
  'Dispel Magic': 'Disipar magia',
  'Divination': 'Adivinación',
  'Divine Favor': 'Favor divino',
  'Divine Word': 'Palabra divina',
  'Dominate Beast': 'Dominar bestia',
  'Dominate Monster': 'Dominar monstruo',
  'Dominate Person': 'Dominar persona',
  'Drawmij\'s Instant Summons': 'Convocación instantánea de Drawmij',
  'Dream': 'Sueño',
  'Druidcraft': 'Truco de druida',
  'Eldritch Blast': 'Descarga sobrenatural',
  'Enhance Ability': 'Mejorar característica',
  'Enlarge/Reduce': 'Aumentar/Reducir',
  'Entangle': 'Enmarañar',
  'Enthrall': 'Cautivar',
  'Etherealness': 'Eterealidad',
  'Expeditious Retreat': 'Retirada expedita',
  'Eyebite': 'Mirada hiriente',
  'Fabricate': 'Fabricar',
  'Faerie Fire': 'Fuego feérico',
  'False Life': 'Falsa vida',
  'Fear': 'Miedo',
  'Feather Fall': 'Caída de pluma',
  'Feeblemind': 'Memoria débil',
  'Feign Death': 'Fingir muerte',
  'Find Familiar': 'Encontrar familiar',
  'Find Steed': 'Encontrar montura',
  'Find Traps': 'Detectar trampas',
  'Find the Path': 'Encontrar el camino',
  'Finger of Death': 'Dedo de muerte',
  'Fire Bolt': 'Descarga de fuego',
  'Fire Shield': 'Escudo de fuego',
  'Fire Storm': 'Tormenta de fuego',
  'Fireball': 'Bola de fuego',
  'Flame Arrow': 'Flecha flamígera',
  'Flame Blade': 'Hoja flamígera',
  'Flame Strike': 'Golpe flamígero',
  'Flaming Sphere': 'Esfera de fuego',
  'Flesh to Stone': 'Carne a piedra',
  'Fly': 'Volar',
  'Fog Cloud': 'Niebla',
  'Forbiddance': 'Prohibición',
  'Forcecage': 'Jaula de fuerza',
  'Foresight': 'Presciencia',
  'Freedom of Movement': 'Libertad de movimiento',
  'Freezing Sphere': 'Esfera congelante',
  'Gaseous Form': 'Forma gaseosa',
  'Gate': 'Portal',
  'Geas': 'Geas',
  'Gentle Repose': 'Reposo apacible',
  'Giant Insect': 'Insecto gigante',
  'Glibness': 'Labia',
  'Globe of Invulnerability': 'Globo de invulnerabilidad',
  'Glyph of Warding': 'Glifo de guardia',
  'Goodberry': 'Baya buena',
  'Grasping Vine': 'Enredadera agarradora',
  'Grease': 'Grasa',
  'Greater Invisibility': 'Invisibilidad mayor',
  'Greater Restoration': 'Restauración superior',
  'Green-Flame Blade': 'Cuchilla de llama verde',
  'Guardian of Faith': 'Guardián de fe',
  'Guards and Wards': 'Guardias y centinelas',
  'Guidance': 'Orientación',
  'Guiding Bolt': 'Rayo guidado',
  'Gust of Wind': 'Ráfaga de viento',
  'Hallow': 'Consagrar',
  'Hallucinatory Terrain': 'Terreno alucinatorio',
  'Harm': 'Dañar',
  'Haste': 'Prisa',
  'Heal': 'Sanar',
  'Healing Word': 'Palabra de curación',
  'Heat Metal': 'Metal al rojo',
  'Hellish Rebuke': 'Castigo infernal',
  'Heroes\' Feast': 'Banquete de héroes',
  'Heroism': 'Heroísmo',
  'Hex': 'Maleficio',
  'Hold Monster': 'Retener monstruo',
  'Hold Person': 'Retener persona',
  'Holy Aura': 'Aura sagrada',
  'Hunger of Hadar': 'Hambre de Hadar',
  'Hunter\'s Mark': 'Marca del cazador',
  'Hypnotic Pattern': 'Patrón hipnótico',
  'Ice Storm': 'Tormenta de hielo',
  'Identify': 'Identificar',
  'Illusory Script': 'Escritura ilusoria',
  'Imprisonment': 'Encarcelamiento',
  'Incendiary Cloud': 'Nube incendiaria',
  'Inflict Wounds': 'Infligir heridas',
  'Insect Plague': 'Plaga de insectos',
  'Inspiration': 'Inspiración',
  'Invisibility': 'Invisibilidad',
  'Jump': 'Salto',
  'Knock': 'Abrir',
  'Legend Lore': 'Saber legendario',
  'Leomund\'s Secret Chest': 'Cofre secreto de Leomund',
  'Leomund\'s Tiny Hut': 'Cabaña diminuta de Leomund',
  'Lesser Restoration': 'Restauración menor',
  'Levitate': 'Levitar',
  'Light': 'Luz',
  'Lightning Arrow': 'Flecha de rayo',
  'Lightning Bolt': 'Rayo',
  'Locate Animals or Plants': 'Localizar animales o plantas',
  'Locate Creature': 'Localizar criatura',
  'Locate Object': 'Localizar objeto',
  'Longstrider': 'Zancada larga',
  'Mage Armor': 'Armadura de mago',
  'Mage Hand': 'Mano de mago',
  'Magic Circle': 'Círculo mágico',
  'Magic Jar': 'Tarro mágico',
  'Magic Missile': 'Proyectil mágico',
  'Magic Mouth': 'Boca mágica',
  'Magic Weapon': 'Arma mágica',
  'Magnificent Mansion': 'Mansión magnifica',
  'Major Image': 'Imagen mayor',
  'Mass Cure Wounds': 'Sanar grupal',
  'Mass Heal': 'Sanar grupo',
  'Mass Healing Word': 'Palabra de sanación grupal',
  'Mass Suggestion': 'Sugestión grupal',
  'Maze': 'Laberinto',
  'Meld into Stone': 'Fundirse en piedra',
  'Mending': 'Reparar',
  'Message': 'Mensaje',
  'Meteor Swarm': 'Lluvia de meteoros',
  'Mighty Fortress': 'Fortaleza poderosa',
  'Mind Blank': 'Mente en blanco',
  'Minor Illusion': 'Ilusión menor',
  'Mirage Arcane': 'Milagro arcano',
  'Mirror Image': 'Doble imagen',
  'Mislead': 'Engaño',
  'Misty Step': 'Paso brumoso',
  'Modify Memory': 'Modificar memoria',
  'Moonbeam': 'Rayo lunar',
  'Mordenkainen\'s Faithful Hound': 'Sabueso fiel de Mordenkainen',
  'Mordenkainen\'s Magnificent Mansion': 'Mansión magnifica de Mordenkainen',
  'Mordenkainen\'s Private Sanctum': 'Santuario privado de Mordenkainen',
  'Move Earth': 'Mover tierra',
  'Nondetection': 'Indetectable',
  'Nystul\'s Magic Aura': 'Aura mágica de Nystul',
  'Otto\'s Irresistible Dance': 'Baile irresistible de Otto',
  'Pass without Trace': 'Pasar sin rastro',
  'Passwall': 'Paso de muro',
  'Phantasmal Force': 'Fuerza fantasmal',
  'Phantasmal Killer': 'Asesino fantasmal',
  'Phantom Steed': 'Caballo fantasma',
  'Planar Ally': 'Aliado planar',
  'Planar Binding': 'Vinculación planar',
  'Plane Shift': 'Cambio de plano',
  'Plant Growth': 'Crecimiento vegetal',
  'Poison Spray': 'Rociada venenosa',
  'Polymorph': 'Polimorfar',
  'Power Word Heal': 'Palabra de poder: sanar',
  'Power Word Kill': 'Palabra de poder: matar',
  'Power Word Stun': 'Palabra de poder: aturdir',
  'Prayer of Healing': 'Oración de sanación',
  'Prestidigitation': 'Prestidigitación',
  'Prismatic Spray': 'Rocío prismático',
  'Prismatic Wall': 'Muro prismático',
  'Produce Flame': 'Producir llama',
  'Programmed Illusion': 'Ilusión programada',
  'Project Image': 'Imagen proyectada',
  'Protection from Energy': 'Protección contra energía',
  'Protection from Evil and Good': 'Protección contra malignidad y bondad',
  'Protection from Poison': 'Protección contra veneno',
  'Purify Food and Drink': 'Purificar comida y bebida',
  'Raise Dead': 'Resucitar muertos',
  'Rary\'s Telepathic Bond': 'Vínculo telepático de Rary',
  'Ray of Enfeeblement': 'Rayo de debilitamiento',
  'Ray of Frost': 'Rayo de escarcha',
  'Ray of Sickness': 'Rayo de enfermedad',
  'Regenerate': 'Regenerar',
  'Reincarnate': 'Reencarnar',
  'Remove Curse': 'Quitar maldición',
  'Resilient Sphere': 'Esfera resiliente',
  'Resistance': 'Resistencia',
  'Resurrection': 'Resurrección',
  'Reverse Gravity': 'Gravedad inversa',
  'Revivify': 'Revivir',
  'Rope Trick': 'Truco de la cuerda',
  'Sacred Flame': 'Llama sagrada',
  'Sanctuary': 'Santuario',
  'Scorching Ray': 'Rayo abrasador',
  'Scrying': 'Escudriñamiento',
  'Sealing Smite': 'Castigo sellador',
  'See Invisibility': 'Ver lo invisible',
  'Seeming': 'Apariencia',
  'Sending': 'Enviar',
  'Sequester': 'Aislar',
  'Shatter': 'Fragmentar',
  'Shield': 'Escudo',
  'Shield of Faith': 'Escudo de fe',
  'Shillelagh': 'Bastón mágico',
  'Shocking Grasp': 'Toque electrizante',
  'Silence': 'Silencio',
  'Silent Image': 'Imagen silenciosa',
  'Simulacrum': 'Simulacro',
  'Sleep': 'Sueño',
  'Sleet Storm': 'Tormenta de aguanieve',
  'Slow': 'Lentitud',
  'Speak with Animals': 'Hablar con los animales',
  'Speak with Dead': 'Hablar con los muertos',
  'Speak with Plants': 'Hablar con las plantas',
  'Spider Climb': 'Trepar como araña',
  'Spike Growth': 'Crecimiento de púas',
  'Spirit Guardians': 'Guardián espiritual',
  'Spiritual Weapon': 'Arma espiritual',
  'Stinking Cloud': 'Nube fétida',
  'Stone Shape': 'Dar forma a la piedra',
  'Stoneskin': 'Piel de piedra',
  'Storm of Vengeance': 'Tormenta de venganza',
  'Suggestion': 'Sugestión',
  'Sunbeam': 'Rayo solar',
  'Sunburst': 'Estallido solar',
  'Symbol': 'Símbolo',
  'Telekinesis': 'Telequinesis',
  'Telepathy': 'Telepatía',
  'Teleport': 'Teletransporte',
  'Teleportation Circle': 'Círculo de teletransporte',
  'Thaumaturgy': 'Taumaturgia',
  'Thunderwave': 'Onda atronadora',
  'Time Stop': 'Detener el tiempo',
  'Tiny Hut': 'Cabaña diminuta',
  'Tongues': 'Lenguas',
  'Transmute Rock': 'Transmutar roca',
  'Transport via Plants': 'Teletransporte por plantas',
  'Tree Stride': 'Paso arbóreo',
  'True Polymorph': 'Polimorfar verdadero',
  'True Resurrection': 'Resurrección verdadera',
  'True Seeing': 'Visión verdadera',
  'True Strike': 'Golpe certero',
  'Unseen Servant': 'Sirviente invisible',
  'Vampiric Touch': 'Toque vampírico',
  'Vicious Mockery': 'Burla cruel',
  'Wall of Fire': 'Muro de fuego',
  'Wall of Force': 'Muro de fuerza',
  'Wall of Ice': 'Muro de hielo',
  'Wall of Stone': 'Muro de piedra',
  'Wall of Thorns': 'Muro de espinas',
  'Warding Bond': 'Vínculo protector',
  'Water Breathing': 'Respirar agua',
  'Water Walk': 'Caminar sobre el agua',
  'Web': 'Telaraña',
  'Weird': 'Rareza',
  'Wind Walk': 'Caminar con el viento',
  'Wish': 'Deseo',
  'Witch Bolt': 'Rayo de bruja',
  'Word of Recall': 'Palabra de regreso',
  'Zone of Truth': 'Zona de verdad',
};

/** Spanish translations of 5e.tools race names. */
export const RACE_NAME_ES: Record<string, string> = {
  // PHB 2024 + classics
  'Aarakocra': 'Aarakocra',
  'Aasimar': 'Aasimar',
  'Dragonborn': 'Dracónido',
  'Drow': 'Drow',
  'Dwarf': 'Enano',
  'Elf': 'Elfo',
  'Githyanki': 'Githyanki',
  'Githzerai': 'Githzerai',
  'Gnome': 'Gnomo',
  'Goliath': 'Goliath',
  'Halfling': 'Mediano',
  'Human': 'Humano',
  'Orc': 'Orco',
  'Tiefling': 'Tiefling',
  // Common SRD 5.2
  'Aetherborn': 'Aetherborn',
  'Air Genasi': 'Genasi del aire',
  'Asmodeus Tiefling': 'Tiefling de Asmodeus',
  'Astral Elf': 'Elfo astral',
  'Autognome': 'Autognomo',
  'Aven': 'Aven',
  'Baeloth': 'Baeloth',
  'Baazrag': 'Baazrag',
  'Bugbear': 'Insectópodo',
  'Centaur': 'Centauro',
  'Changeling': 'Cambiaformas',
  'Chondathan Human': 'Humano Chondathan',
  'Chuul': 'Chuul',
  'Cowardice Devil': 'Diablo de la cobardía',
  'Custom Lineage': 'Linaje personalizado',
  'Cyclops': 'Cíclope',
  'Dakkon': 'Dakkon',
  'Dao': 'Dao',
  'Dark Elf': 'Elfo oscuro',
  'Deep Gnome': 'Gnomo profundo',
  'Derro': 'Derro',
  'Dhampir': 'Dhampir',
  'Dimir Vampire': 'Vampiro Dimir',
  'Dragonborn of the Sea': 'Dracónido del mar',
  'Dread': 'Pavor',
  'Duergar': 'Duergar',
  'Durthan': 'Durthan',
  'Earth Genasi': 'Genasi de la tierra',
  'Eladrin': 'Eladrin',
  'Ethereal Filcher': 'Robador etéreo',
  'Evereskan Half-Elf': 'Semielfo de Evereska',
  'Fairy': 'Hada',
  'Falkyr': 'Falkyr',
  'Far': 'Lejos',
  'Fell': 'Caída',
  'Fenris': 'Fenris',
  'Fiend': 'Demonio',
  'Fighter': 'Guerrero',
  'Fire Genasi': 'Genasi del fuego',
  'Firbolg': 'Firbolg',
  'Fisher': 'Pescador',
  'Forest Gnome': 'Gnomo del bosque',
  'Gargoyle': 'Gárgola',
  'Genasi': 'Genasi',
  'Ghostwise Halfling': 'Mediano de la voz fantasmal',
  'Ghoul': 'Espectro devorador',
  'Giant': 'Gigante',
  'Gith': 'Gith',
  'Goblin': 'Goblin',
  'Graz\'zt': 'Graz\'zt',
  'Grimlock': 'Grimlock',
  'Grippli': 'Grippli',
  'Gull': 'Gaviota',
  'Half-Elf': 'Semielfo',
  'Half-Orc': 'Semiorco',
  'Harengon': 'Harengón',
  'High Elf': 'Alto elfo',
  'Hill Dwarf': 'Enano de las colinas',
  'Hobgoblin': 'Hobgoblin',
  'Hollow One': 'Hueco',
  'Illuskan Human': 'Humano Illuskan',
  'Incorporeal Undead': 'No-muerto incorpóreo',
  'Kalashtar': 'Kalashtar',
  'Kenku': 'Kenku',
  'Khenra': 'Khenra',
  'Kobold': 'Kóbold',
  'Kor': 'Kor',
  'Lizardfolk': 'Pueblo lagarto',
  'Locathah': 'Locathah',
  'Loxodon': 'Loxodon',
  'Mariner Human': 'Humano marinero',
  'Marisa': 'Marisa',
  'Meazel': 'Meazel',
  'Merfolk': 'Pueblo del mar',
  'Minotaur': 'Minotauro',
  'Mountain Dwarf': 'Enano de la montaña',
  'Naga': 'Naga',
  'Nautical Halfling': 'Mediano náutico',
  'Necropolitan': 'Necropolitan',
  'Noble Genasi': 'Genasi noble',
  'Ogre': 'Ogro',
  'Oni': 'Oni',
  'Owlin': 'Owlin',
  'Pixie': 'Pixie',
  'Protector Aasimar': 'Aasimar protector',
  'Quetzal': 'Quetzal',
  'Rakshasa': 'Rakshasa',
  'Reborn': 'Renacido',
  'Revenant': 'Vengador',
  'Roc': 'Roc',
  'Rock Gnome': 'Gnomo de las rocas',
  'Sahuagin': 'Sahuagin',
  'Satyr': 'Sátiro',
  'Scourge Aasimar': 'Aasimar flagelador',
  'Sea Elf': 'Elfo del mar',
  'Seer': 'Vidente',
  'Sentient Construct': 'Constructo inteligente',
  'Shadar-kai': 'Shadar-kai',
  'Shadow': 'Sombra',
  'Shalish': 'Shalish',
  'Shifter': 'Cambiante',
  'Simic Hybrid': 'Híbrido Simic',
  'Skeleton': 'Esqueleto',
  'Slippery': 'Resbaladizo',
  'Sphinx': 'Esfinge',
  'Sprite': 'Hada',
  'Strix': 'Strix',
  'Svifneblin': 'Svifneblin',
  'Tabaxi': 'Tabaxi',
  'Tortle': 'Tortle',
  'Triton': 'Tritón',
  'Vampire': 'Vampiro',
  'Vedalken': 'Vedalken',
  'Verdan': 'Verdan',
  'Water Genasi': 'Genasi del agua',
  'Werebear': 'Hombre-oso',
  'Wereboar': 'Hombre-jabalí',
  'Weretiger': 'Hombre-tigre',
  'Werewolf': 'Hombre-lobo',
  'Wilden': 'Wilden',
  'Wood Elf': 'Elfo del bosque',
  'Worg': 'Worg',
  'Yuan-ti': 'Yuan-ti',
  'Yuan-ti Pureblood': 'Yuan-ti pura sangre',
  'Zariel Tiefling': 'Tiefling de Zariel',
};

/** Spanish translations of 5e.tools class names. */
export const CLASS_NAME_ES: Record<string, string> = {
  'Barbarian': 'Bárbaro',
  'Bard': 'Bardo',
  'Cleric': 'Clérigo',
  'Druid': 'Druida',
  'Fighter': 'Guerrero',
  'Monk': 'Monje',
  'Paladin': 'Paladín',
  'Ranger': 'Explorador',
  'Rogue': 'Pícaro',
  'Sorcerer': 'Hechicero',
  'Warlock': 'Brujo',
  'Wizard': 'Mago',
  'Artificer': 'Artificiero',
  'Mystic': 'Místico',
  'Sidekick': 'Compañero',
  'Champion': 'Campeón',
  'Cavalier': 'Caballero',
  'Banneret': 'Banderizo',
  'Samurai': 'Samurái',
  'Arcane Archer': 'Arquero arcano',
  'Eldritch Knight': 'Caballero sobrenatural',
  'Battle Master': 'Maestro de batalla',
  'Path of the Ancestral Guardian': 'Camino del guardián ancestral',
  'Path of the Berserker': 'Camino del berserker',
  'Path of the Storm Herald': 'Camino del heraldo de la tormenta',
  'Path of the Totem Warrior': 'Camino del guerrero tótem',
  'Path of the Zealot': 'Camino del fanático',
  'Path of Wild Magic': 'Camino de la magia salvaje',
  'College of Lore': 'Colegio del saber',
  'College of Valor': 'Colegio del valor',
  'College of Glamour': 'Colegio del glamour',
  'College of Swords': 'Colegio de las espadas',
  'College of Whispers': 'Colegio de los susurros',
  'Life Domain': 'Dominio de la vida',
  'Light Domain': 'Dominio de la luz',
  'Nature Domain': 'Dominio de la naturaleza',
  'Tempest Domain': 'Dominio de la tempestad',
  'Trickery Domain': 'Dominio del engaño',
  'War Domain': 'Dominio de la guerra',
  'Death Domain': 'Dominio de la muerte',
  'Knowledge Domain': 'Dominio del conocimiento',
  'Order Domain': 'Dominio del orden',
  'Peace Domain': 'Dominio de la paz',
  'Twilight Domain': 'Dominio del crepúsculo',
  'Circle of the Land': 'Círculo de la tierra',
  'Circle of the Moon': 'Círculo de la luna',
  'Circle of the Shepherd': 'Círculo del pastor',
  'Circle of Spores': 'Círculo de las esporas',
  'Circle of Stars': 'Círculo de las estrellas',
  'Circle of Wildfire': 'Círculo del fuego salvaje',
  'Way of the Open Hand': 'Camino de la mano abierta',
  'Way of Shadow': 'Camino de la sombra',
  'Way of the Four Elements': 'Camino de los cuatro elementos',
  'Way of Mercy': 'Camino de la misericordia',
  'Way of the Astral Self': 'Camino del yo astral',
  'Way of the Drunken Master': 'Camino del maestro borracho',
  'Way of the Kensei': 'Camino del kensei',
  'Way of the Long Death': 'Camino de la larga muerte',
  'Way of the Sun Soul': 'Camino del alma solar',
  'Oath of Devotion': 'Juramento de devoción',
  'Oath of the Ancients': 'Juramento de los antiguos',
  'Oath of Vengeance': 'Juramento de venganza',
  'Oath of Conquest': 'Juramento de conquista',
  'Oath of Redemption': 'Juramento de redención',
  'Oath of Glory': 'Juramento de gloria',
  'Oath of the Watchers': 'Juramento de los vigilantes',
  'Oath of the Crown': 'Juramento de la corona',
  'Oathbreaker': 'Rompajuros',
  'Beast Master': 'Maestro de bestias',
  'Hunter': 'Cazador',
  'Gloom Stalker': 'Acechador de la penumbra',
  'Horizon Walker': 'Caminante del horizonte',
  'Monster Slayer': 'Cazador de monstruos',
  'Primeval Guardian': 'Guardián primordial',
  'Swarmkeeper': 'Guardián de enjambre',
  'Drakewarden': 'Guardián de dracos',
  'Arcane Trickster': 'Trickster arcano',
  'Assassin': 'Asesino',
  'Mastermind': 'Mente maestra',
  'Phantom': 'Fantasma',
  'Soulknife': 'Cuchilla del alma',
  'Swashbuckler': 'Espadachín',
  'Thief': 'Ladrón',
  'Wild Magic': 'Magia salvaje',
  'Draconic Bloodline': 'Linaje dracónico',
  'Aberrant Mind': 'Mente aberrante',
  'Clockwork Soul': 'Alma de relojería',
  'Divine Soul': 'Alma divina',
  'Shadow Magic': 'Magia de las sombras',
  'Storm Sorcery': 'Hechicería de tormenta',
  'Wild Magic (Sorcerer)': 'Magia salvaje (hechicero)',
  'The Archfey': 'El Archi-hada',
  'The Celestial': 'El celestial',
  'The Fiend': 'El infernal',
  'The Great Old One': 'El gran antiguo',
  'The Hexblade': 'El maldito',
  'The Undead': 'El no-muerto',
  'The Undying': 'El inmortal',
  'The Undead (UA)': 'El no-muerto (UA)',
  'School of Abjuration': 'Escuela de abjuración',
  'School of Conjuration': 'Escuela de conjuración',
  'School of Divination': 'Escuela de adivinación',
  'School of Enchantment': 'Escuela de encantamiento',
  'School of Evocation': 'Escuela de evocación',
  'School of Illusion': 'Escuela de ilusión',
  'School of Necromancy': 'Escuela de nigromancia',
  'School of Transmutation': 'Escuela de transmutación',
  'Bladesinging': 'Canto de las espadas',
  'War Magic': 'Magia de guerra',
};
