/**
 * SRD 5.2 spell → class mapping.
 *
 * 5e.tools data does not tag spells with their class list — the frontend
 * filters by class using the source book (e.g. PHB = Wizard/Sorcerer/
 * Warlock/Bard). We hand-curate the SRD 5.2 class list per spell so the
 * `spells(classId)` query returns a meaningful subset.
 *
 * IDs match `spells-xphb.json` and `spells-phb.json` from the 5etools data,
 * lowercased + slugified (see `build-5etools.mjs`).
 */
import type { AbilityKey } from '../types.js';

export type ClassId = 'barbarian' | 'bard' | 'cleric' | 'druid' | 'fighter' | 'monk' | 'paladin' | 'ranger' | 'rogue' | 'sorcerer' | 'warlock' | 'wizard';

/**
 * Map a spell slug (5e.tools id) to its class list. Spells not in the map
 * are considered utility spells any class can pick up via subclass.
 */
export const SPELL_CLASS_MAP: Record<string, ClassId[]> = {
  // Cantrips
  'acid-splash': ['sorcerer', 'wizard'],
  'blade-ward': ['sorcerer', 'warlock', 'wizard', 'bard'],
  'chill-touch': ['sorcerer', 'warlock', 'wizard'],
  'dancing-lights': ['bard', 'sorcerer', 'wizard'],
  'druidcraft': ['druid'],
  'eldritch-blast': ['warlock'],
  'fire-bolt': ['sorcerer', 'wizard'],
  'friends': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'guidance': ['cleric', 'druid'],
  'light': ['bard', 'cleric', 'sorcerer', 'wizard'],
  'mage-hand': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'mending': ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
  'message': ['bard', 'sorcerer', 'wizard'],
  'minor-illusion': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'poison-spray': ['druid', 'sorcerer', 'warlock', 'wizard'],
  'prestidigitation': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'produce-flame': ['druid'],
  'ray-of-frost': ['sorcerer', 'wizard'],
  'resistance': ['cleric', 'druid'],
  'sacred-flame': ['cleric'],
  'shillelagh': ['druid'],
  'shocking-grasp': ['sorcerer', 'wizard'],
  'spare-the-dying': ['cleric'],
  'thaumaturgy': ['cleric'],
  'thorn-whip': ['druid'],
  'true-strike': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'vicious-mockery': ['bard'],
  // Level 1
  'alarm': ['ranger', 'wizard'],
  'animal-friendship': ['bard', 'druid', 'ranger'],
  'bane': ['bard', 'cleric', 'paladin'],
  'bless': ['cleric', 'paladin'],
  'burning-hands': ['sorcerer', 'wizard'],
  'charm-person': ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
  'color-spray': ['sorcerer', 'wizard'],
  'command': ['cleric', 'paladin'],
  'comprehend-languages': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'create-or-destroy-water': ['cleric', 'druid'],
  'cure-wounds': ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  'detect-evil-and-good': ['cleric', 'paladin'],
  'detect-magic': ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'],
  'detect-poison-and-disease': ['cleric', 'druid', 'paladin', 'ranger'],
  'disguise-self': ['bard', 'sorcerer', 'wizard'],
  'divine-favor': ['paladin'],
  'entangle': ['druid'],
  'expeditious-retreat': ['sorcerer', 'warlock', 'wizard'],
  'faerie-fire': ['bard', 'druid'],
  'false-life': ['bard', 'sorcerer', 'wizard'],
  'feather-fall': ['bard', 'sorcerer', 'wizard'],
  'find-familiar': ['wizard'],
  'fog-cloud': ['druid', 'sorcerer', 'wizard'],
  'grease': ['sorcerer', 'wizard'],
  'guiding-bolt': ['cleric'],
  'healing-word': ['bard', 'cleric', 'druid'],
  'hellish-rebuke': ['warlock'],
  'heroism': ['bard', 'paladin'],
  'hideous-laughter': ['bard', 'wizard'],
  'hunters-mark': ['ranger'],
  'identify': ['bard', 'wizard'],
  'illusory-script': ['bard', 'warlock', 'wizard'],
  'inflict-wounds': ['cleric'],
  'jump': ['druid', 'ranger', 'sorcerer', 'wizard'],
  'longstrider': ['druid', 'ranger', 'wizard'],
  'mage-armor': ['sorcerer', 'wizard'],
  'magic-missile': ['sorcerer', 'wizard'],
  'protection-from-evil-and-good': ['cleric', 'paladin', 'warlock', 'wizard'],
  'purify-food-and-drink': ['cleric', 'druid', 'paladin'],
  'ray-of-sickness': ['sorcerer', 'wizard'],
  'sanctuary': ['cleric'],
  'shield': ['sorcerer', 'wizard'],
  'shield-of-faith': ['cleric', 'paladin'],
  'silent-image': ['bard', 'sorcerer', 'wizard'],
  'sleep': ['bard', 'sorcerer', 'wizard'],
  'speak-with-animals': ['bard', 'druid', 'ranger'],
  'thunderwave': ['bard', 'druid', 'sorcerer', 'wizard'],
  'unseen-servant': ['bard', 'warlock', 'wizard'],
  'witch-bolt': ['sorcerer', 'warlock', 'wizard'],
  // Level 2
  'aid': ['cleric', 'paladin'],
  'alter-self': ['sorcerer', 'warlock', 'wizard'],
  'arcane-lock': ['wizard'],
  'arcanists-magic-aura': ['wizard'],
  'augury': ['cleric', 'druid'],
  'blindness-deafness': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  'blur': ['sorcerer', 'warlock', 'wizard'],
  'calm-emotions': ['bard', 'cleric'],
  'cloud-of-daggers': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'continual-flame': ['cleric', 'wizard'],
  'cordon-of-arrows': ['ranger'],
  'cure-wounds-2': ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  'darkness': ['sorcerer', 'warlock', 'wizard'],
  'darkvision': ['druid', 'sorcerer', 'warlock', 'wizard'],
  'detect-thoughts': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'enhance-ability': ['bard', 'cleric', 'druid', 'sorcerer', 'wizard'],
  'enlarge-reduce': ['sorcerer', 'wizard'],
  'enthrall': ['bard', 'warlock', 'wizard'],
  'find-traps': ['cleric', 'druid', 'ranger'],
  'flame-blade': ['druid'],
  'flaming-sphere': ['druid', 'sorcerer', 'wizard'],
  'gentle-repose': ['cleric', 'warlock', 'wizard'],
  'gust-of-wind': ['druid', 'sorcerer', 'wizard'],
  'heat-metal': ['bard', 'druid'],
  'hold-person': ['bard', 'cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
  'invisibility': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'knock': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'lesser-restoration': ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  'levitate': ['sorcerer', 'wizard'],
  'locate-object': ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  'magic-mouth': ['bard', 'wizard'],
  'magic-weapon': ['cleric', 'paladin', 'warlock', 'wizard'],
  'mirror-image': ['sorcerer', 'warlock', 'wizard'],
  'misty-step': ['sorcerer', 'warlock', 'wizard'],
  'moonbeam': ['druid'],
  'pass-without-trace': ['druid', 'ranger'],
  'phantasmal-force': ['bard', 'sorcerer', 'wizard'],
  'prayer-of-healing': ['cleric', 'paladin'],
  'protection-from-poison': ['cleric', 'druid', 'paladin', 'ranger'],
  'ray-of-enfeeblement': ['sorcerer', 'warlock', 'wizard'],
  'rope-trick': ['sorcerer', 'warlock', 'wizard'],
  'scorching-ray': ['sorcerer', 'wizard'],
  'see-invisibility': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'shatter': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'silence': ['bard', 'cleric', 'ranger'],
  'silent-image-2': ['bard', 'sorcerer', 'wizard'],
  'spider-climb': ['druid', 'sorcerer', 'warlock', 'wizard'],
  'spike-growth': ['druid', 'ranger'],
  'spiritual-weapon': ['cleric'],
  'suggestion': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'web': ['sorcerer', 'wizard'],
  'zone-of-truth': ['bard', 'cleric', 'paladin'],
  // Level 3
  'animate-dead': ['cleric', 'warlock', 'wizard'],
  'aura-of-vitality': ['paladin'],
  'beacon-of-hope': ['cleric', 'paladin'],
  'bestow-curse': ['bard', 'cleric', 'warlock', 'wizard'],
  'blink': ['sorcerer', 'warlock', 'wizard'],
  'call-lightning': ['druid'],
  'clairvoyance': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  'conjure-animals': ['druid', 'ranger'],
  'conjure-barrage': ['fighter', 'ranger'],
  'counterspell': ['sorcerer', 'warlock', 'wizard'],
  'create-food-and-water': ['cleric', 'paladin'],
  'daylight': ['cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'],
  'dispel-magic': ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'warlock', 'wizard'],
  'dispel-magic-3': ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'warlock', 'wizard'],
  'fear': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'feign-death': ['cleric', 'druid', 'warlock', 'wizard'],
  'fireball': ['sorcerer', 'wizard'],
  'flame-arrow': ['ranger', 'sorcerer', 'wizard'],
  'fly': ['sorcerer', 'warlock', 'wizard'],
  'gaseous-form': ['sorcerer', 'warlock', 'wizard'],
  'glyph-of-warding': ['bard', 'cleric', 'wizard'],
  'haste': ['sorcerer', 'wizard'],
  'hold-monster': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  'hunger-of-hadar': ['warlock', 'wizard'],
  'hypnotic-pattern': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'lightning-bolt': ['sorcerer', 'wizard'],
  'magic-circle': ['cleric', 'paladin', 'warlock', 'wizard'],
  'major-image': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'mass-cure-wounds': ['bard', 'cleric', 'druid'],
  'mass-healing-word': ['cleric', 'druid'],
  'meld-into-stone': ['druid', 'ranger', 'sorcerer', 'wizard'],
  'nondetection': ['bard', 'ranger', 'warlock', 'wizard'],
  'phantom-steed': ['wizard'],
  'plant-growth': ['bard', 'druid', 'ranger'],
  'protection-from-energy': ['cleric', 'druid', 'paladin', 'ranger', 'sorcerer', 'wizard'],
  'remove-curse': ['cleric', 'paladin', 'warlock', 'wizard'],
  'revivify': ['cleric', 'paladin'],
  'sending': ['bard', 'cleric', 'warlock', 'wizard'],
  'sleet-storm': ['druid', 'sorcerer', 'wizard'],
  'slow': ['sorcerer', 'warlock', 'wizard'],
  'speak-with-dead': ['bard', 'cleric'],
  'speak-with-plants': ['bard', 'druid', 'ranger'],
  'spirit-guardians': ['cleric'],
  'stinking-cloud': ['bard', 'sorcerer', 'wizard'],
  'tiny-hut': ['bard', 'wizard'],
  'tongues': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  'vampiric-touch': ['sorcerer', 'warlock', 'wizard'],
  'water-breathing': ['druid', 'ranger', 'sorcerer', 'wizard'],
  'water-walk': ['cleric', 'druid', 'ranger', 'sorcerer'],
  // Level 4
  'arcane-eye': ['wizard'],
  'banishment': ['cleric', 'paladin', 'sorcerer', 'warlock', 'wizard'],
  'blight': ['druid', 'sorcerer', 'warlock', 'wizard'],
  'compulsion': ['bard'],
  'confusion': ['bard', 'druid', 'sorcerer', 'wizard'],
  'conjure-minor-elementals': ['druid', 'wizard'],
  'conjure-woodland-beings': ['druid', 'ranger'],
  'control-water': ['cleric', 'druid', 'wizard'],
  'death-ward': ['cleric', 'paladin'],
  'dimension-door': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'divination': ['cleric', 'druid'],
  'dominate-beast': ['druid', 'sorcerer', 'wizard'],
  'fabricate': ['wizard'],
  'fire-shield': ['sorcerer', 'wizard'],
  'freedom-of-movement': ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  'giant-insect': ['druid'],
  'greater-invisibility': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'guardian-of-faith': ['cleric'],
  'hallucinatory-terrain': ['bard', 'druid', 'warlock', 'wizard'],
  'ice-storm': ['druid', 'sorcerer', 'wizard'],
  'leomunds-secret-chest': ['wizard'],
  'locate-creature': ['bard', 'cleric', 'druid', 'paladin', 'ranger', 'wizard'],
  'mordenkainens-faithful-hound': ['wizard'],
  'mordenkainens-private-sanctum': ['wizard'],
  'otilukes-resilient-sphere': ['sorcerer', 'wizard'],
  'phantasmal-killer': ['wizard'],
  'polymorph': ['bard', 'druid', 'sorcerer', 'wizard'],
  'stone-shape': ['cleric', 'druid', 'wizard'],
  'stoneskin': ['druid', 'ranger', 'sorcerer', 'wizard'],
  'storm-shell': ['ranger', 'sorcerer', 'wizard'],
  'wall-of-fire': ['druid', 'sorcerer', 'wizard'],
  'wall-of-thorns': ['druid'],
  // Level 5
  'animate-objects': ['bard', 'sorcerer', 'wizard'],
  'antilife-shell': ['druid'],
  'arcane-hand': ['wizard'],
  'awaken': ['bard', 'druid'],
  'banishing-smite': ['paladin'],
  'bigbys-hand': ['wizard'],
  'circle-of-power': ['paladin'],
  'cloudkill': ['sorcerer', 'wizard'],
  'commune': ['cleric'],
  'cone-of-cold': ['sorcerer', 'wizard'],
  'conjure-elemental': ['druid', 'wizard'],
  'conjure-fey': ['druid', 'warlock', 'wizard'],
  'contact-other-plane': ['warlock', 'wizard'],
  'contagion': ['cleric', 'druid'],
  'creation': ['sorcerer', 'wizard'],
  'cure-wounds-5': ['bard', 'cleric', 'druid'],
  'dismissal': ['cleric', 'paladin', 'sorcerer', 'warlock', 'wizard'],
  'dominate-person': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'dream': ['bard', 'druid', 'warlock', 'wizard'],
  'flame-strike': ['cleric'],
  'geas': ['bard', 'cleric', 'druid', 'paladin', 'warlock', 'wizard'],
  'greater-restoration': ['bard', 'cleric', 'druid', 'paladin', 'ranger'],
  'hold-monster-5': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  'holy-atonement': ['cleric', 'paladin'],
  'insect-plague': ['cleric', 'druid', 'ranger', 'sorcerer'],
  'legend-lore': ['bard', 'cleric', 'wizard'],
  'mass-cure-wounds-5': ['bard', 'cleric', 'druid'],
  'mislead': ['bard', 'warlock', 'wizard'],
  'modify-memory': ['bard', 'warlock', 'wizard'],
  'passwall': ['wizard'],
  'planar-binding': ['bard', 'cleric', 'druid', 'warlock', 'wizard'],
  'raise-dead': ['bard', 'cleric', 'paladin'],
  'rarys-telepathic-bond': ['wizard'],
  'reincarnate': ['druid'],
  'scrying': ['bard', 'cleric', 'druid', 'warlock', 'wizard'],
  'seeming': ['bard', 'sorcerer', 'wizard'],
  'telekinesis': ['sorcerer', 'wizard'],
  'telepathic-bond': ['wizard'],
  'teleportation-circle': ['bard', 'sorcerer', 'wizard'],
  'tree-stride': ['druid', 'ranger'],
  'wall-of-force': ['sorcerer', 'warlock', 'wizard'],
  'wall-of-stone': ['druid', 'sorcerer', 'wizard'],
  // Level 6
  'arcane-gate': ['sorcerer', 'warlock', 'wizard'],
  'blade-barrier': ['cleric'],
  'bones-of-the-earth': ['druid'],
  'chain-lightning': ['sorcerer', 'wizard'],
  'circle-of-death': ['sorcerer', 'warlock', 'wizard'],
  'conjure-fey-6': ['druid', 'warlock', 'wizard'],
  'create-undead': ['cleric', 'warlock', 'wizard'],
  'disintegrate': ['sorcerer', 'wizard'],
  'drawmijs-instant-summons': ['wizard'],
  'eyebite': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'flesh-to-stone': ['sorcerer', 'wizard'],
  'forbiddance': ['cleric', 'wizard'],
  'globe-of-invulnerability': ['sorcerer', 'wizard'],
  'guards-and-wards': ['bard', 'wizard'],
  'harm': ['cleric'],
  'heal': ['cleric', 'druid'],
  'heroes-feast': ['bard', 'cleric', 'druid'],
  'irresistible-dance': ['bard', 'wizard'],
  'mass-suggestion': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'mental-prison': ['sorcerer', 'warlock', 'wizard'],
  'move-earth': ['druid', 'sorcerer', 'wizard'],
  'ottos-irresistible-dance': ['bard', 'wizard'],
  'planar-ally': ['cleric', 'warlock', 'wizard'],
  'programmed-illusion': ['bard', 'wizard'],
  'sunbeam': ['druid', 'sorcerer', 'wizard'],
  'true-seeing': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  'transport-via-plants': ['druid'],
  'wall-of-ice': ['sorcerer', 'wizard'],
  'wall-of-thorns-6': ['druid'],
  'wind-walk': ['druid'],
  'word-of-recall': ['cleric', 'druid', 'wizard'],
  // Level 7
  'conjure-celestial': ['cleric'],
  'delayed-blast-fireball': ['sorcerer', 'wizard'],
  'divine-word': ['cleric'],
  'etherealness': ['bard', 'cleric', 'sorcerer', 'warlock', 'wizard'],
  'finger-of-death': ['sorcerer', 'warlock', 'wizard'],
  'fire-storm': ['cleric', 'druid', 'sorcerer', 'wizard'],
  'forcecage': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'magnificent-mansion': ['bard', 'wizard'],
  'mighty-fortress': ['wizard'],
  'plane-shift': ['cleric', 'druid', 'sorcerer', 'warlock', 'wizard'],
  'prismatic-spray': ['sorcerer', 'wizard'],
  'project-image': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'regenerate': ['bard', 'cleric', 'druid'],
  'resurrection': ['bard', 'cleric'],
  'revivify-7': ['cleric', 'paladin'],
  'reverse-gravity': ['druid', 'sorcerer', 'wizard'],
  'sequester': ['warlock', 'wizard'],
  'simulacrum': ['warlock', 'wizard'],
  'symbol': ['bard', 'cleric', 'wizard'],
  'teleport': ['bard', 'sorcerer', 'wizard'],
  // Level 8
  'antimagic-field': ['cleric', 'wizard'],
  'antipathy-sympathy': ['druid', 'wizard'],
  'clone': ['wizard'],
  'control-weather': ['cleric', 'druid', 'wizard'],
  'demiplane': ['warlock', 'wizard'],
  'dominate-monster': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'earthquake': ['cleric', 'druid', 'sorcerer'],
  'feeblemind': ['bard', 'druid', 'warlock', 'wizard'],
  'glibness': ['bard', 'warlock', 'wizard'],
  'holy-aura': ['cleric'],
  'horrid-wilting': ['sorcerer', 'warlock', 'wizard'],
  'incendiary-cloud': ['sorcerer', 'wizard'],
  'maddening-darkness': ['warlock'],
  'maze': ['wizard'],
  'mind-blank': ['bard', 'warlock', 'wizard'],
  'power-word-stun': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'sunburst': ['cleric', 'druid', 'sorcerer', 'wizard'],
  'telepathy': ['wizard'],
  // Level 9
  'astral-projection': ['cleric', 'warlock', 'wizard'],
  'foresight': ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
  'gate': ['cleric', 'sorcerer', 'warlock', 'wizard'],
  'imprisonment': ['warlock', 'wizard'],
  'mass-heal': ['cleric'],
  'meteor-swarm': ['sorcerer', 'wizard'],
  'power-word-kill': ['bard', 'sorcerer', 'warlock', 'wizard'],
  'prismatic-wall': ['wizard'],
  'shapechange': ['druid', 'sorcerer', 'wizard'],
  'storm-of-vengeance': ['druid'],
  'time-stop': ['sorcerer', 'wizard'],
  'true-polymorph': ['bard', 'druid', 'sorcerer', 'warlock', 'wizard'],
  'true-resurrection': ['cleric', 'druid'],
  'weird': ['wizard'],
  'wish': ['sorcerer', 'wizard'],
};

/**
 * In the Spanish UI, an ability key may be selected at level-up. This
 * map provides a default suggestion per class, but the player may pick any.
 */
export const CLASS_PRIMARY_ABILITY: Record<ClassId, AbilityKey[]> = {
  barbarian: ['str'],
  bard: ['cha'],
  cleric: ['wis'],
  druid: ['wis'],
  fighter: ['str', 'dex'],
  monk: ['dex', 'wis'],
  paladin: ['str', 'cha'],
  ranger: ['dex', 'wis'],
  rogue: ['dex'],
  sorcerer: ['cha'],
  warlock: ['cha'],
  wizard: ['int'],
};
